import type { StoreData } from '../shared/types.js';

export const DEFAULT_STORE_DATA: StoreData = {
    vertexAiApiKey: '',
    visionApiKey: '',
    gcpProject: '',
    gcpLocation: 'global',
    geminiModel: 'gemini-2.5-flash-lite',
    vertexAiSupportsImages: false,
    geminiMediaResolution: 'default',
    allowedGuildIds: [],
    lensEnabledGuildIds: [],
    allowedUserIds: [],
    cooldownSeconds: 5,
    cacheMaxSize: 2000,
    setupComplete: false,
    inputPricePerMillion: 0,
    outputPricePerMillion: 0,
    dailyBudgetUsd: 0,
    visionMonthlyImageLimit: 900,
    defaultUserDailyBudgetUsd: 0,
    tokenUsage: null,
    usageHistory: [],
    translationPrompt: '',
    userLanguagePrefs: {},
    userLanguagePreferenceEntries: [],
    maxInputLength: 2000,
    maxOutputTokens: 4096,
    translationMaxConcurrent: 4,
    translationMaxGlobalQueue: 25,
    translationMaxGuildQueue: 5,
    translationMaxUserOutstanding: 1,
    translationMaxQueueWaitMs: 30000,
    openaiApiKey: '',
    openaiBaseUrl: '',
    openaiModel: '',
    openaiSupportsImages: false,
    translationProvider: 'vertex',
    guildBudgets: {},
    guildVisionLimits: {},
    guildTokenUsage: {},
    guildUsageHistory: {},
    userBudgets: {},
    userVisionLimits: {},
    userTokenUsage: {},
    userUsageHistory: {},
};

export const CONFIG_VALUE_KEYS = [
    'vertexAiApiKey',
    'visionApiKey',
    'gcpProject',
    'gcpLocation',
    'geminiModel',
    'vertexAiSupportsImages',
    'geminiMediaResolution',
    'allowedGuildIds',
    'lensEnabledGuildIds',
    'allowedUserIds',
    'cooldownSeconds',
    'cacheMaxSize',
    'setupComplete',
    'inputPricePerMillion',
    'outputPricePerMillion',
    'dailyBudgetUsd',
    'visionMonthlyImageLimit',
    'defaultUserDailyBudgetUsd',
    'translationPrompt',
    'maxInputLength',
    'maxOutputTokens',
    'translationMaxConcurrent',
    'translationMaxGlobalQueue',
    'translationMaxGuildQueue',
    'translationMaxUserOutstanding',
    'translationMaxQueueWaitMs',
    'openaiApiKey',
    'openaiBaseUrl',
    'openaiModel',
    'openaiSupportsImages',
    'translationProvider',
] as const satisfies readonly (keyof StoreData)[];

export type ConfigValueKey = (typeof CONFIG_VALUE_KEYS)[number];
