import { chmodSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { DatabaseSync } from 'node:sqlite';

interface TableExport {
    table: string;
    columns: string[];
    select?: string;
}

function sqlValue(value: unknown): string {
    if (value === null || value === undefined) return 'NULL';
    if (typeof value === 'number') {
        if (!Number.isFinite(value)) throw new Error('Cannot export a non-finite number');
        return String(value);
    }
    return `'${String(value).replace(/'/g, "''")}'`;
}

function hasTable(db: DatabaseSync, table: string): boolean {
    return !!db.prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?").get(table);
}

function hasColumn(db: DatabaseSync, table: string, column: string): boolean {
    return (db.prepare(`PRAGMA table_info("${table}")`).all() as Array<{ name: string }>).some(
        (row) => row.name === column,
    );
}

export function buildD1ImportSql(db: DatabaseSync): string {
    const glossaryLanguage = hasColumn(db, 'guild_glossary', 'target_language')
        ? 'target_language'
        : "'auto' AS target_language";
    const tables: TableExport[] = [
        {
            table: 'app_config',
            columns: ['key', 'value', 'updated_at'],
            select: "SELECT key, value_json AS value, datetime('now') AS updated_at FROM app_config",
        },
        {
            table: 'user_language_preferences',
            columns: ['guild_id', 'user_id', 'language'],
        },
        { table: 'guild_budgets', columns: ['guild_id', 'daily_budget_usd'] },
        { table: 'user_budgets', columns: ['user_id', 'daily_budget_usd'] },
        {
            table: 'daily_usage',
            columns: ['id', 'date', 'input_tokens', 'output_tokens', 'requests'],
        },
        {
            table: 'guild_daily_usage',
            columns: ['guild_id', 'date', 'input_tokens', 'output_tokens', 'requests'],
        },
        {
            table: 'user_daily_usage',
            columns: ['user_id', 'date', 'input_tokens', 'output_tokens', 'requests'],
        },
        {
            table: 'usage_history',
            columns: ['date', 'input_tokens', 'output_tokens', 'requests'],
        },
        {
            table: 'guild_usage_history',
            columns: ['guild_id', 'date', 'input_tokens', 'output_tokens', 'requests'],
        },
        {
            table: 'user_usage_history',
            columns: ['user_id', 'date', 'input_tokens', 'output_tokens', 'requests'],
        },
        {
            table: 'guild_glossary',
            columns: [
                'id',
                'guild_id',
                'source_text',
                'target_language',
                'target_text',
                'notes',
                'created_at',
                'updated_at',
            ],
            select: `SELECT id, guild_id, source_text, ${glossaryLanguage}, target_text,
                            notes, created_at, updated_at FROM guild_glossary`,
        },
        {
            table: 'pending_user_install_owners',
            columns: ['user_id', 'last_seen_at'],
            select: 'SELECT user_id, last_seen_at FROM pending_user_install_owners',
        },
    ];

    const output = [
        '-- Generated by npm run db:export:d1. Treat this file as sensitive.',
        'PRAGMA foreign_keys = OFF;',
    ];
    for (const spec of tables) {
        if (!hasTable(db, spec.table)) continue;
        const query = spec.select ?? `SELECT ${spec.columns.join(', ')} FROM ${spec.table}`;
        const rows = db.prepare(query).all() as Array<Record<string, unknown>>;
        for (const row of rows) {
            output.push(
                `INSERT OR REPLACE INTO ${spec.table} (${spec.columns.join(', ')}) VALUES (${spec.columns
                    .map((column) => sqlValue(row[column]))
                    .join(',')});`,
            );
        }
    }
    output.push('PRAGMA foreign_keys = ON;', '');
    return output.join('\n');
}

function run(): void {
    const input = resolve(process.argv[2] ?? 'data/babel.sqlite');
    const output = resolve(process.argv[3] ?? 'backups/babel-d1-import.sql');
    const db = new DatabaseSync(input, { readOnly: true });
    try {
        mkdirSync(dirname(output), { recursive: true });
        writeFileSync(output, buildD1ImportSql(db), { mode: 0o600 });
        chmodSync(output, 0o600);
        console.log(`[D1 Export] Wrote ${output} from ${input}`);
    } finally {
        db.close();
    }
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) run();
